# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cody Sullins
title: Computer Scientist | Aspiring IT Professional | Never Settle
email: c.sullins24@gmail.com
website: www.github.com/salhounz

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: CodySullins
github_username:  salhounz
linkedin_username: SullinsCody
# stackoverflow_username: username_goes_here
# dribbble_username: username_goes_here
# facebook_username: username_goes_here
# flickr_username: username_goes_here
# instagram_username: username_goes_here

# xing_username: username_goes_here
# pinterest_username: username_goes_here
# youtube_username: username_goes_here
# googleplus_username: username_goes_here
# orcid_username: username_goes_here

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.randomwebsite.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Cody Sullins and I am a Senior at Missouri State University pursuing a Bachelor of Science in Computer Science - Software Development with a minor in Cybersecurity as well as an Undergraduate Certificate in Web Programming although I am also beginning an Accelerated Master of Science in Cybersecurity starting this Fall. In addition,
  to academics I am apart of a few groups at Missouri State that are Digital Coffee and Kappa Sigma and I have served a multitude of roles within those groups in order to help facilitate and grow each into the best organization possible.
  I am mostly skilled in: <mark>Web Development</mark> <mark>Problem Solving/Creative Thinking</mark> <mark>Customer Service</mark> and <mark>Leadership</mark>
content:
  - title: Projects # Section Title
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Digital Coffee
        link: https://discord.gg/tTB6RUW5vS
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A collaborative space for Computer Science students, clubs, groups, and those interested to boost study skills, knowledge, network, and increase communication between the Computer Science department and its students with over 280 members and growing!
        description: | # this will include new lines to allow paragraphs
           I began this project my Sophomore year of college with 2 other people whom simply wanted to increase communication between students as once class would be over the helpful communication and banter between students and professors would cease as well. So, we
           started a Discord server with that idea in mind as there were no other options available for us and now with over 280 memebers and an rotating administration team of 5 we have class-selection abilities to form groups within classes, networking oppourtunities (LinkedIn, etc.), job and internship postings, and over 8 clubs and groups posted within our server
           including an original dynamic open world (4km X 4km) RPG with dynamic plants, animals, AI controlled NPC's, lifelike simulations of erosion, gradual population, and many other effects made by multiple members of Digital Coffee. The other groups include GDG Springfield, Springfield Devs, Data Science After Dark, and Springfield Women in Technology.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: Missouri State University
        link: helpdesk.missouristate.edu
        link_text: missouristate.edu
        sub_title: Open-Access Lab Assistant
        caption: September 2017 - Present
        quote: >
          2019 Student Employee of The Year Nominee
        description: | # this will include new lines to allow paragraphs
            Provide technical support to students, faculty, and staff using any of Missouri State University's systems and services within one of the three Open-Access Computer Labs on campus as well as any remote locations that university networks/hardware is being utilized.
     
     - layout: left
        title: O'Reilly Auto Parts, Inc. - Home Office
        link: oreillyauto.com
        # link_text: oreillyauto.com
        sub_title: Junior Software Developer
        caption: August 2019 - January 2020
        description: | # this will include new lines to allow paragraphs
            Debug and correct exisiting software defects, develop new and modify existing software, create/update project documentation.
      
      - layout: left
        title: O'Reilly Auto Parts, Inc. - Home Office
        link: oreillyauto.com
        # link_text: oreillyauto.com
        sub_title: Intern Software Developer
        caption: May 2019 - August 2019
        description: | # this will include new lines to allow paragraphs
            The O'Reilly Auto Parts Software Developer Internship is an internship that begins with a 12-week classroom period to train each intern.
            This training period is taught by internship supervisors from O'Reilly Auto Parts and is hosted at Missouri State University. The program consists of both classroom training and hands-on experience in a lab environment.
 
 - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
