# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cody Sullins
title: Computer Scientist | Aspiring IT Professional | Never Settle
email: c.sullins24@gmail.com
website: www.github.com/salhounz

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: CodySullins
github_username:  salhounz
linkedin_username: SullinsCody
# stackoverflow_username: username_goes_here
# dribbble_username: username_goes_here
# facebook_username: username_goes_here
# flickr_username: username_goes_here
# instagram_username: username_goes_here

# xing_username: username_goes_here
# pinterest_username: username_goes_here
# youtube_username: username_goes_here
# googleplus_username: username_goes_here
# orcid_username: username_goes_here

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.randomwebsite.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Cody Sullins and I am a Senior at Missouri State University pursuing a Bachelor of Science in Computer Science - Software Development with a minor in Cybersecurity as well as an Undergraduate Certificate in Web Programming although I am also beginning an Accelerated Master of Science in Cybersecurity starting this Fall. In addition,
  to academics I am apart of a few groups at Missouri State that are Digital Coffee and Kappa Sigma and I have served a multitude of roles within those groups in order to help facilitate and grow each into the best organization possible.
  I am mostly skilled in: <mark>Web Development</mark> <mark>Problem Solving/Creative Thinking</mark> and <mark>Leadership</mark>

content:
  - title: Projects # Section Title
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Digital Coffee
        link: https://discord.gg/tTB6RUW5vS
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A collaborative space for Computer Science students, clubs, groups, and those interested to boost study skills, knowledge, networking, and also just increasing communication between the Computer Science department and students with over 250 members and growing!
        description: | # this will include new lines to allow paragraphs
           I began this project my Sophomore year of college with 2 other people whom simply wanted to increase communication between students as once class would be over the helpful communication would cease as well. So, we
           started a Discord server with that idea in mind as there were no other options for us and now with over 250 memebers and an administration team of 5 we have class-selection abilities to form groups within classes, networking oppourtunities (LinkedIn, etc.), job and internship postings, and over 8 clubs and groups posted within our server
           including an original dynamic open world (4km X 4km) RPG with dynamic plants, animals, AI controlled NPC's, lifelike simulations of erosion, gradual population, and many others. The other groups include GDG Springfield, Springfield Devs, Data Science After Dark, and Springfield Women in Technology.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
